version: '3'
services:
  indscraper:
    build:
      context: ./indscraper
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml


  tech_pipe:
    build:
      context: ./tech_pipe
      dockerfile: Dockerfile